/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

declare const _SWIG_type_tag: unique symbol;

export  class Circle {

  m_radius: number;

  constructor(radius: number);

  area(): number;

  perimeter(): number;
}


